version: 0.2

env:
  variables:
    REPO_URI: <ACCOUNT_ID>.dkr.ecr.ap-south-2.amazonaws.com/backend-prod

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region ap-south-2 | docker login --username AWS --password-stdin $REPO_URI
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION

  build:
    commands:
      - docker build -t backend-prod:$IMAGE_TAG .
      - docker tag backend-prod:$IMAGE_TAG $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - docker push $REPO_URI:$IMAGE_TAG
      - printf '[{"name":"backend","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - appspec.yml
    - docker-compose.yml
    - scripts/deploy.sh
    - imagedefinitions.json
