version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-2
    AWS_ACCOUNT_ID: 331301815990
    IMAGE_REPO_NAME: backend-prod

phases:

  pre_build:
    commands:
      - echo Logging into Amazon ECR
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Building Docker image
      - docker build -t backend-prod .
      - docker tag backend-prod:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/backend-prod:latest

  post_build:
    commands:
      - echo Pushing image to ECR
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/backend-prod:latest

artifacts:
  files:
    - appspec.yml
    - docker-compose.yml
    - scripts/deploy.sh
